<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <AssemblyName>JeffopolyDeal</AssemblyName>
    <RootNamespace>JeffopolyDeal</RootNamespace>
    <Configurations>Debug;Release</Configurations>
    <DefaultItemExcludes>$(DefaultItemExcludes);..\..\node_modules\**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="JeffopolyDeal.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\JeffopolyDeal.Shared\JeffopolyDeal.Shared.csproj" />
    <ProjectReference Include="..\JeffopolyDeal.BotAI\JeffopolyDeal.BotAI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\wwwroot\**" LinkBase="wwwroot" CopyToOutputDirectory="Never" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="Themes\**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="*" />
  </ItemGroup>
</Project>
